# JNVM configuration

# Input JAR
jar: test/114514.jar

# Output JAR
out: test/114514-obf.jar

# Protect rules
protect:
  - "**"

# Optional exclude rules
# exclude:
#   - "com.example.Main#main"

# Optional: explicit Zig executable path.
# When omitted, JNVM scans for a sibling folder like:
#   zig-x86_64-windows-0.14.0/zig.exe
# zig-exe: D:/tools/zig/zig.exe

# Optional: compile targets.
# When omitted, JNVM uses the current platform automatically.
targets:
  - x86_64-windows-gnu

# Generated native source directory
native-dir: native

# Options
encrypt-strings: false
debug: false
direct-native-rewrite: false
