jar: bench/bench.jar
out: bench/bench-obf.jar

protect:
  - "**"

# zig-exe: D:/tools/zig/zig.exe
# targets:
#   - x86_64-windows-gnu

native-dir: ../native/bench
encrypt-strings: false
debug: false
direct-native-rewrite: false
