jar: demo/demo.jar
out: demo/demo-obf.jar

protect:
  - "**"

# zig-exe: D:/tools/zig/zig.exe
# targets:
#   - x86_64-windows-gnu

native-dir: ../native/demo
encrypt-strings: false
debug: false
direct-native-rewrite: false
