jar: zkm/SnakeGame-zkm.jar
out: zkm/SnakeGame-zkm-obf.jar

protect:
  - "**"

# zig-exe: D:/tools/zig/zig.exe
# targets:
#   - x86_64-windows-gnu

native-dir: ../native/zkm
encrypt-strings: false
debug: false
direct-native-rewrite: false
