jar: snake/SnakeGame.jar
out: snake/SnakeGame-obf.jar

protect:
  - "**"

# zig-exe: D:/tools/zig/zig.exe
# targets:
#   - x86_64-windows-gnu

native-dir: ../native/snake
encrypt-strings: false
debug: false
direct-native-rewrite: false
